# Identificação do projeto no Sonar
sonar.projectKey=13SOAT-andromeda_video-processor-users-api
sonar.projectName=Video Processor Users API
sonar.projectVersion=1.0

# Fontes do código
sonar.sources=.
sonar.security.sources=.

# Excluir arquivos de teste e infraestrutura de banco de dados da análise principal
sonar.exclusions=**/*_test.go,**/repository/**,**/router.go,**/model/**,**/cmd/api/main.go,**/cmd/worker/main.go,**/internal/adapter/config/**,**/internal/adapter/database/postgres.go,**/internal/adapter/database/seeder.go

# Para testes
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/repository/**

# Relatório de cobertura (gerado pelo go test)
sonar.go.coverage.reportPaths=coverage.out

# Codificação
sonar.sourceEncoding=UTF-8
