name: CI/CD
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  ci:
    if: github.event_name == 'pull_request'
    uses: 13SOAT-andromeda/tech-andromeda-ci-config/.github/workflows/reusable-go-ci.yml@v1
    secrets: inherit

  cd:
    needs: ci
    if: always() && (needs.ci.result == 'success' || needs.ci.result == 'skipped')
    permissions:
      contents: read
      pull-requests: write
    uses: 13SOAT-andromeda/tech-andromeda-ci-config/.github/workflows/reusable-eks-cd.yml@v1
    with:
      ecr-repository: video-processor-users-api-prod
      dockerfile: Dockerfile
      docker-target: production
      kustomize-overlay: k8s/overlays/aws
      deployments: video-processor-users-api video-processor-users-api-worker
    secrets: inherit
