name: CI/CD
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  ci:
    uses: 13SOAT-andromeda/tech-andromeda-ci-config/.github/workflows/reusable-go-ci.yml@v1
    with:
      sonar-project-key: 13SOAT-andromeda_video-processor-users-api
    secrets: inherit

  cd:
    needs: ci
    uses: 13SOAT-andromeda/tech-andromeda-ci-config/.github/workflows/reusable-eks-cd.yml@v1
    with:
      ecr-repository: video-processor-users-api-prod
      dockerfile: Dockerfile
      docker-target: production
      kustomize-overlay: k8s/overlays/aws
      deployments: video-processor-users-api video-processor-users-api-worker
    secrets: inherit
