name: SonarQube / SonarCloud Scan

on:
  pull_request:
    branches: [ main, develop, release/**, feature/**]

jobs:
  sonar:
    name: Analyze with Sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=13soat-andromeda
            -Dsonar.projectKey=13SOAT-andromeda_video-processor-users-api
            -Dsonar.go.coverage.reportPaths=coverage.out
